.PHONY: install clean

PROTO_DIR=../../backend/grpc-api-types/proto

install:
	@echo "Installing dependencies..."
	@npm install
	@echo "Dependencies installed!"

clean:
	@echo "Cleaning node_modules..."
	@rm -rf node_modules
	@echo "Clean complete!"
